<?php

namespace ContainerXdIeHGY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LqN1anyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.LqN1any' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.LqN1any'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'httpClient' => ['privates', '.debug.http_client', 'get_Debug_HttpClientService', false],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'params' => ['privates', 'parameter_bag', 'getParameterBagService', false],
        ], [
            'httpClient' => '?',
            'logger' => '?',
            'params' => '?',
        ]);
    }
}
