<?php

namespace ContainerVVv0F1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_JbohuSpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.JbohuSp' shared service.
     *
     * @return \App\Service\GeocodingService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $geocodingService argument is type-hinted with the non-existent class or interface: "App\\Service\\GeocodingService".');
    }
}
