<?php

namespace ContainerVVv0F1x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y9lzMvLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Y9lzMvL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Y9lzMvL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espaceSportifRepository' => ['privates', 'App\\Repository\\EspacesportifRepository', 'getEspacesportifRepositoryService', true],
            'geocodingService' => ['privates', '.errored.JbohuSp', NULL, 'Cannot determine controller argument for "App\\Controller\\HomeController::index()": the $geocodingService argument is type-hinted with the non-existent class or interface: "App\\Service\\GeocodingService".'],
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'espaceSportifRepository' => 'App\\Repository\\EspacesportifRepository',
            'geocodingService' => '?',
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
        ]);
    }
}
