<?php

namespace Container3Tu50wU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZE9R63eService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZE9R63e' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZE9R63e'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historiqueClubRepository' => ['privates', 'App\\Repository\\HistoriqueClubRepository', 'getHistoriqueClubRepositoryService', true],
        ], [
            'historiqueClubRepository' => 'App\\Repository\\HistoriqueClubRepository',
        ]);
    }
}
