<?php

namespace Container3Tu50wU;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IoGT2SMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ioGT2SM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ioGT2SM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espaceSportifRepository' => ['privates', 'App\\Repository\\EspacesportifRepository', 'getEspacesportifRepositoryService', true],
            'knpSnappyPdf' => ['privates', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
        ], [
            'espaceSportifRepository' => 'App\\Repository\\EspacesportifRepository',
            'knpSnappyPdf' => 'Knp\\Snappy\\Pdf',
        ]);
    }
}
