<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAAfxPa4\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAAfxPa4/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAAfxPa4.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAAfxPa4\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAAfxPa4\App_KernelDevDebugContainer([
    'container.build_hash' => 'AAfxPa4',
    'container.build_id' => '26e9731b',
    'container.build_time' => 1745699345,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAAfxPa4');
