<?php

namespace ContainerA4XBJaJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DfsAOXDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dfsAOXD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dfsAOXD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ClubController::delete' => ['privates', '.service_locator.GbJZUn8', 'get_ServiceLocator_GbJZUn8Service', true],
            'App\\Controller\\ClubController::edit' => ['privates', '.service_locator.GbJZUn8', 'get_ServiceLocator_GbJZUn8Service', true],
            'App\\Controller\\ClubController::index' => ['privates', '.service_locator.eOJlB0r', 'get_ServiceLocator_EOJlB0rService', true],
            'App\\Controller\\ClubController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClubController::statistics' => ['privates', '.service_locator.eOJlB0r', 'get_ServiceLocator_EOJlB0rService', true],
            'App\\Controller\\ContratController::delete' => ['privates', '.service_locator.46d3SGC', 'get_ServiceLocator_46d3SGCService', true],
            'App\\Controller\\ContratController::edit' => ['privates', '.service_locator.46d3SGC', 'get_ServiceLocator_46d3SGCService', true],
            'App\\Controller\\ContratController::export' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\ContratController::index' => ['privates', '.service_locator.8H.sdZM', 'get_ServiceLocator_8H_SdZMService', true],
            'App\\Controller\\ContratController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ContratController::show' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\JoueurController::index' => ['privates', '.service_locator.i0N9PQM', 'get_ServiceLocator_I0N9PQMService', true],
            'App\\Controller\\SponsorController::delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SponsorController::edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SponsorController::export' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\SponsorController::main' => ['privates', '.service_locator.8H.sdZM', 'get_ServiceLocator_8H_SdZMService', true],
            'App\\Controller\\SponsorController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SportController::delete' => ['privates', '.service_locator.geVFa8t', 'get_ServiceLocator_GeVFa8tService', true],
            'App\\Controller\\SportController::edit' => ['privates', '.service_locator.geVFa8t', 'get_ServiceLocator_GeVFa8tService', true],
            'App\\Controller\\SportController::index' => ['privates', '.service_locator.jpL5_4q', 'get_ServiceLocator_JpL54qService', true],
            'App\\Controller\\SportController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SportController::statistics' => ['privates', '.service_locator.cX9LP_Y', 'get_ServiceLocator_CX9LPYService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ClubController:delete' => ['privates', '.service_locator.GbJZUn8', 'get_ServiceLocator_GbJZUn8Service', true],
            'App\\Controller\\ClubController:edit' => ['privates', '.service_locator.GbJZUn8', 'get_ServiceLocator_GbJZUn8Service', true],
            'App\\Controller\\ClubController:index' => ['privates', '.service_locator.eOJlB0r', 'get_ServiceLocator_EOJlB0rService', true],
            'App\\Controller\\ClubController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ClubController:statistics' => ['privates', '.service_locator.eOJlB0r', 'get_ServiceLocator_EOJlB0rService', true],
            'App\\Controller\\ContratController:delete' => ['privates', '.service_locator.46d3SGC', 'get_ServiceLocator_46d3SGCService', true],
            'App\\Controller\\ContratController:edit' => ['privates', '.service_locator.46d3SGC', 'get_ServiceLocator_46d3SGCService', true],
            'App\\Controller\\ContratController:export' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\ContratController:index' => ['privates', '.service_locator.8H.sdZM', 'get_ServiceLocator_8H_SdZMService', true],
            'App\\Controller\\ContratController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\ContratController:show' => ['privates', '.service_locator.0TK7yZ8', 'get_ServiceLocator_0TK7yZ8Service', true],
            'App\\Controller\\JoueurController:index' => ['privates', '.service_locator.i0N9PQM', 'get_ServiceLocator_I0N9PQMService', true],
            'App\\Controller\\SponsorController:delete' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SponsorController:edit' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SponsorController:export' => ['privates', '.service_locator.MPUuYf0', 'get_ServiceLocator_MPUuYf0Service', true],
            'App\\Controller\\SponsorController:main' => ['privates', '.service_locator.8H.sdZM', 'get_ServiceLocator_8H_SdZMService', true],
            'App\\Controller\\SponsorController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SportController:delete' => ['privates', '.service_locator.geVFa8t', 'get_ServiceLocator_GeVFa8tService', true],
            'App\\Controller\\SportController:edit' => ['privates', '.service_locator.geVFa8t', 'get_ServiceLocator_GeVFa8tService', true],
            'App\\Controller\\SportController:index' => ['privates', '.service_locator.jpL5_4q', 'get_ServiceLocator_JpL54qService', true],
            'App\\Controller\\SportController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\SportController:statistics' => ['privates', '.service_locator.cX9LP_Y', 'get_ServiceLocator_CX9LPYService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ClubController::delete' => '?',
            'App\\Controller\\ClubController::edit' => '?',
            'App\\Controller\\ClubController::index' => '?',
            'App\\Controller\\ClubController::new' => '?',
            'App\\Controller\\ClubController::statistics' => '?',
            'App\\Controller\\ContratController::delete' => '?',
            'App\\Controller\\ContratController::edit' => '?',
            'App\\Controller\\ContratController::export' => '?',
            'App\\Controller\\ContratController::index' => '?',
            'App\\Controller\\ContratController::new' => '?',
            'App\\Controller\\ContratController::show' => '?',
            'App\\Controller\\JoueurController::index' => '?',
            'App\\Controller\\SponsorController::delete' => '?',
            'App\\Controller\\SponsorController::edit' => '?',
            'App\\Controller\\SponsorController::export' => '?',
            'App\\Controller\\SponsorController::main' => '?',
            'App\\Controller\\SponsorController::new' => '?',
            'App\\Controller\\SportController::delete' => '?',
            'App\\Controller\\SportController::edit' => '?',
            'App\\Controller\\SportController::index' => '?',
            'App\\Controller\\SportController::new' => '?',
            'App\\Controller\\SportController::statistics' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ClubController:delete' => '?',
            'App\\Controller\\ClubController:edit' => '?',
            'App\\Controller\\ClubController:index' => '?',
            'App\\Controller\\ClubController:new' => '?',
            'App\\Controller\\ClubController:statistics' => '?',
            'App\\Controller\\ContratController:delete' => '?',
            'App\\Controller\\ContratController:edit' => '?',
            'App\\Controller\\ContratController:export' => '?',
            'App\\Controller\\ContratController:index' => '?',
            'App\\Controller\\ContratController:new' => '?',
            'App\\Controller\\ContratController:show' => '?',
            'App\\Controller\\JoueurController:index' => '?',
            'App\\Controller\\SponsorController:delete' => '?',
            'App\\Controller\\SponsorController:edit' => '?',
            'App\\Controller\\SponsorController:export' => '?',
            'App\\Controller\\SponsorController:main' => '?',
            'App\\Controller\\SponsorController:new' => '?',
            'App\\Controller\\SportController:delete' => '?',
            'App\\Controller\\SportController:edit' => '?',
            'App\\Controller\\SportController:index' => '?',
            'App\\Controller\\SportController:new' => '?',
            'App\\Controller\\SportController:statistics' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
