<?php

namespace ContainerZkbo0Kj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GfugV81Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gfugV81' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gfugV81'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationPhysiqueRepository', 'getEvaluationPhysiqueRepositoryService', true],
            'joueurRepository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'performanceRepository' => ['privates', 'App\\Repository\\PerformanceJoueurRepository', 'getPerformanceJoueurRepositoryService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\EvaluationPhysiqueRepository',
            'joueurRepository' => 'App\\Repository\\JoueurRepository',
            'paginator' => '?',
            'performanceRepository' => 'App\\Repository\\PerformanceJoueurRepository',
        ]);
    }
}
