# config/packages/framework.yaml
framework:
    asset_mapper:
        # Paths to scan for assets, relative to the project root
        paths:
            - assets/
        # Strict mode ensures errors are thrown for missing imports during development
        missing_import_mode: strict

when@prod:
    framework:
        asset_mapper:
            # In production, warn instead of throwing errors for missing imports
            missing_import_mode: warn