# config/packages/messenger.yaml
framework:
    messenger:
        transports:
            async:
                dsn: 'doctrine://default?queue_name=messages'
            failed:
                dsn: 'doctrine://default?queue_name=failed'