framework:
  notifier:
    chatter_transports:
      # no chatter transports
    texter_transports:
    channel_policy:
      # only email
      urgent: ['email']
      high: ['email']
      medium: ['email']
      low: ['email']
    admin_recipients:
      - { email: admin@example.com }