twig:
    file_name_pattern: '*.twig'
    paths:
        '%kernel.project_dir%/front': front
        '%kernel.project_dir%/templates/': templates

    globals:
        recaptcha_site_key: '%recaptcha_site_key%'
when@test:
    twig:
        strict_variables: true
