<?php

namespace ContainerPtzLRBv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZPKYcSnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zPKYcSn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zPKYcSn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historiqueClubRepository' => ['privates', '.errored.QUm_12n', NULL, 'Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::findCurrentPlayersByClub()": the $historiqueClubRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\HistoriqueClubRepository". Did you forget to add a use statement?'],
        ], [
            'historiqueClubRepository' => '?',
        ]);
    }
}
