<?php

namespace ContainerBm8UTxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0rRbLLeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0rRbLLe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0rRbLLe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contratRepository' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'knpSnappyPdf' => ['privates', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
        ], [
            'contratRepository' => 'App\\Repository\\ContratRepository',
            'knpSnappyPdf' => 'Knp\\Snappy\\Pdf',
        ]);
    }
}
