<?php

namespace ContainerBm8UTxD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStripeClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'Stripe\StripeClient' shared autowired service.
     *
     * @return \Stripe\StripeClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stripe'.\DIRECTORY_SEPARATOR.'stripe-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'BaseStripeClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stripe'.\DIRECTORY_SEPARATOR.'stripe-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'StripeClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stripe'.\DIRECTORY_SEPARATOR.'stripe-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'StripeStreamingClientInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stripe'.\DIRECTORY_SEPARATOR.'stripe-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'BaseStripeClient.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'stripe'.\DIRECTORY_SEPARATOR.'stripe-php'.\DIRECTORY_SEPARATOR.'lib'.\DIRECTORY_SEPARATOR.'StripeClient.php';

        return $container->privates['Stripe\\StripeClient'] = new \Stripe\StripeClient($container->getEnv('STRIPE_SECRET_KEY'));
    }
}
