<?php

namespace ContainerLqO2gG0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFootballAnalysisControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\FootballAnalysisController' shared autowired service.
     *
     * @return \App\Controller\FootballAnalysisController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'FootballAnalysisController.php';

        $container->services['App\\Controller\\FootballAnalysisController'] = $instance = new \App\Controller\FootballAnalysisController();

        $instance->setContainer(($container->privates['.service_locator.5zAhzgv'] ?? $container->load('get_ServiceLocator_5zAhzgvService'))->withContext('App\\Controller\\FootballAnalysisController', $container));

        return $instance;
    }
}
