<?php

namespace ContainerN6ZxWoT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PNlbJGOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PNlbJGO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PNlbJGO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'performanceJoueur' => ['privates', '.errored..service_locator.PNlbJGO.App\\Entity\\PerformanceJoueur', NULL, 'Cannot autowire service ".service_locator.PNlbJGO": it needs an instance of "App\\Entity\\PerformanceJoueur" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'performanceJoueur' => 'App\\Entity\\PerformanceJoueur',
        ]);
    }
}
