<?php

namespace ContainerOEGC802;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RCuzfnbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RCuzfnb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RCuzfnb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
            'repository' => ['privates', 'App\\Repository\\MaterielRepository', 'getMaterielRepositoryService', true],
        ], [
            'paginator' => '?',
            'repository' => 'App\\Repository\\MaterielRepository',
        ]);
    }
}
