<?php

namespace ContainerXED4jZ1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N8st8m4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n8st8m4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n8st8m4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evaluationPhysique' => ['privates', '.errored..service_locator.n8st8m4.App\\Entity\\EvaluationPhysique', NULL, 'Cannot autowire service ".service_locator.n8st8m4": it needs an instance of "App\\Entity\\EvaluationPhysique" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'evaluationPhysique' => 'App\\Entity\\EvaluationPhysique',
        ]);
    }
}
