<?php

namespace ContainerFizuMOd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEvaluationPhysiqueService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Nm9r6bo.App\Entity\EvaluationPhysique' shared service.
     *
     * @return \App\Entity\EvaluationPhysique
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Nm9r6bo": it needs an instance of "App\\Entity\\EvaluationPhysique" but this type has been excluded in "config/services.yaml".');
    }
}
