<?php

namespace ContainerOFxP0HI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FFEnhRjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FFEnhRj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FFEnhRj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'historiqueClubRepository' => ['privates', 'App\\Repository\\HistoriqueClubRepository', 'getHistoriqueClubRepositoryService', true],
            'knpSnappyPdf' => ['privates', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
        ], [
            'historiqueClubRepository' => 'App\\Repository\\HistoriqueClubRepository',
            'knpSnappyPdf' => 'Knp\\Snappy\\Pdf',
        ]);
    }
}
