<?php

namespace ContainerOFxP0HI;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SYFRzfMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SYFRzfM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SYFRzfM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationPhysiqueRepository', 'getEvaluationPhysiqueRepositoryService', true],
            'performanceRepository' => ['privates', 'App\\Repository\\PerformanceJoueurRepository', 'getPerformanceJoueurRepositoryService', true],
        ], [
            'entityManager' => '?',
            'evaluationRepository' => 'App\\Repository\\EvaluationPhysiqueRepository',
            'performanceRepository' => 'App\\Repository\\PerformanceJoueurRepository',
        ]);
    }
}
