<?php

namespace Container8o3hEk4;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0qaldgnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0qaldgn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0qaldgn'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'anthropometryRepository' => ['privates', '.errored.8XP71m4', NULL, 'Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::evaluationsByJoueur()": the $anthropometryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AnthropometryRepository". Did you forget to add a use statement?'],
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationPhysiqueRepository', 'getEvaluationPhysiqueRepositoryService', true],
            'flexibilityEvaluationRepository' => ['privates', '.errored.DXsbKV3', NULL, 'Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::evaluationsByJoueur()": the $flexibilityEvaluationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\FlexibilityEvaluationRepository". Did you forget to add a use statement?'],
            'joueurRepository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
        ], [
            'anthropometryRepository' => '?',
            'evaluationRepository' => 'App\\Repository\\EvaluationPhysiqueRepository',
            'flexibilityEvaluationRepository' => '?',
            'joueurRepository' => 'App\\Repository\\JoueurRepository',
        ]);
    }
}
