<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNELt5DT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNELt5DT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNELt5DT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNELt5DT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNELt5DT\App_KernelDevDebugContainer([
    'container.build_hash' => 'NELt5DT',
    'container.build_id' => '7e869eab',
    'container.build_time' => 1746102964,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNELt5DT');
