<?php

namespace ContainerHHdRBET;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_QUm12nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.QUm_12n' shared service.
     *
     * @return \App\Controller\HistoriqueClubRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::findCurrentPlayersByClub()": the $historiqueClubRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\HistoriqueClubRepository". Did you forget to add a use statement?');
    }
}
