<?php

namespace ContainerOp4m7ks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BKFX8uService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BKF_x8u' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BKF_x8u'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'evaluationRepository' => ['privates', 'App\\Repository\\EvaluationPhysiqueRepository', 'getEvaluationPhysiqueRepositoryService', true],
            'performanceRepository' => ['privates', 'App\\Repository\\PerformanceJoueurRepository', 'getPerformanceJoueurRepositoryService', true],
        ], [
            'evaluationRepository' => 'App\\Repository\\EvaluationPhysiqueRepository',
            'performanceRepository' => 'App\\Repository\\PerformanceJoueurRepository',
        ]);
    }
}
