<?php

namespace ContainerOp4m7ks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SOvyuUuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SOvyuUu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SOvyuUu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contratRepository' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'knpSnappyPdf' => ['privates', '.errored.Bgto62a', NULL, 'Cannot determine controller argument for "App\\Controller\\ContratController::export()": the $knpSnappyPdf argument is type-hinted with the non-existent class or interface: "App\\Controller\\Pdf". Did you forget to add a use statement?'],
        ], [
            'contratRepository' => 'App\\Repository\\ContratRepository',
            'knpSnappyPdf' => '?',
        ]);
    }
}
