<?php

namespace ContainerOp4m7ks;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_Bgto62aService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.Bgto62a' shared service.
     *
     * @return \App\Controller\Pdf
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ContratController::export()": the $knpSnappyPdf argument is type-hinted with the non-existent class or interface: "App\\Controller\\Pdf". Did you forget to add a use statement?');
    }
}
