<?php

namespace ContainerBRO4LcH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNoScheduleOverlapValidatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Validator\NoScheduleOverlapValidator' shared autowired service.
     *
     * @return \App\Validator\NoScheduleOverlapValidator
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidatorInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'validator'.\DIRECTORY_SEPARATOR.'ConstraintValidator.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Validator'.\DIRECTORY_SEPARATOR.'NoScheduleOverlapValidator.php';

        return $container->privates['App\\Validator\\NoScheduleOverlapValidator'] = new \App\Validator\NoScheduleOverlapValidator(($container->privates['App\\Repository\\ScheduleRepository'] ?? $container->load('getScheduleRepositoryService')));
    }
}
