<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Joueur extends \App\Entity\Joueur implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'idJoueur' => [parent::class, 'idJoueur', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'poids' => [parent::class, 'poids', null, 16],
        "\0".parent::class."\0".'poste' => [parent::class, 'poste', null, 16],
        "\0".parent::class."\0".'prenom' => [parent::class, 'prenom', null, 16],
        "\0".parent::class."\0".'profilePictureUrl' => [parent::class, 'profilePictureUrl', null, 16],
        "\0".parent::class."\0".'sport' => [parent::class, 'sport', null, 16],
        "\0".parent::class."\0".'statut' => [parent::class, 'statut', null, 16],
        "\0".parent::class."\0".'taille' => [parent::class, 'taille', null, 16],
        "\0".parent::class."\0".'telephone' => [parent::class, 'telephone', null, 16],
        'dateNaissance' => [parent::class, 'dateNaissance', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'idJoueur' => [parent::class, 'idJoueur', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'poids' => [parent::class, 'poids', null, 16],
        'poste' => [parent::class, 'poste', null, 16],
        'prenom' => [parent::class, 'prenom', null, 16],
        'profilePictureUrl' => [parent::class, 'profilePictureUrl', null, 16],
        'sport' => [parent::class, 'sport', null, 16],
        'statut' => [parent::class, 'statut', null, 16],
        'taille' => [parent::class, 'taille', null, 16],
        'telephone' => [parent::class, 'telephone', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
