<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Sponsor extends \App\Entity\Sponsor implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'contact' => [parent::class, 'contact', null, 16],
        "\0".parent::class."\0".'contrats' => [parent::class, 'contrats', null, 16],
        "\0".parent::class."\0".'nom' => [parent::class, 'nom', null, 16],
        "\0".parent::class."\0".'pack' => [parent::class, 'pack', null, 16],
        "\0".parent::class."\0".'sponsorPicture' => [parent::class, 'sponsorPicture', null, 16],
        'Id_sponsor' => [parent::class, 'Id_sponsor', null, 4],
        'contact' => [parent::class, 'contact', null, 16],
        'contrats' => [parent::class, 'contrats', null, 16],
        'nom' => [parent::class, 'nom', null, 16],
        'pack' => [parent::class, 'pack', null, 16],
        'sponsorPicture' => [parent::class, 'sponsorPicture', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
