<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class MatchEntity extends \App\Entity\MatchEntity implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'c1' => [parent::class, 'c1', null, 16],
        "\0".parent::class."\0".'c2' => [parent::class, 'c2', null, 16],
        "\0".parent::class."\0".'idMatch' => [parent::class, 'idMatch', null, 16],
        "\0".parent::class."\0".'schedules' => [parent::class, 'schedules', null, 16],
        "\0".parent::class."\0".'sportType' => [parent::class, 'sportType', null, 16],
        'c1' => [parent::class, 'c1', null, 16],
        'c2' => [parent::class, 'c2', null, 16],
        'idMatch' => [parent::class, 'idMatch', null, 16],
        'schedules' => [parent::class, 'schedules', null, 16],
        'sportType' => [parent::class, 'sportType', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
