<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Espacesportif extends \App\Entity\Espacesportif implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null, 16],
        "\0".parent::class."\0".'capacite' => [parent::class, 'capacite', null, 16],
        "\0".parent::class."\0".'categorie' => [parent::class, 'categorie', null, 16],
        "\0".parent::class."\0".'id_lieu' => [parent::class, 'id_lieu', null, 16],
        "\0".parent::class."\0".'nom_espace' => [parent::class, 'nom_espace', null, 16],
        "\0".parent::class."\0".'reservations' => [parent::class, 'reservations', null, 16],
        'adresse' => [parent::class, 'adresse', null, 16],
        'capacite' => [parent::class, 'capacite', null, 16],
        'categorie' => [parent::class, 'categorie', null, 16],
        'id_lieu' => [parent::class, 'id_lieu', null, 16],
        'nom_espace' => [parent::class, 'nom_espace', null, 16],
        'reservations' => [parent::class, 'reservations', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
