<?php

namespace ContainerZciTDiV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RjBDxh1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rjBDxh1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rjBDxh1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espaceSportifRepository' => ['privates', 'App\\Repository\\EspacesportifRepository', 'getEspacesportifRepositoryService', true],
            'geocodingService' => ['privates', 'App\\Service\\GeocodingService', 'getGeocodingServiceService', true],
        ], [
            'espaceSportifRepository' => 'App\\Repository\\EspacesportifRepository',
            'geocodingService' => 'App\\Service\\GeocodingService',
        ]);
    }
}
