<?php

namespace ContainerS8yOEuk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_8XP71m4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.8XP71m4' shared service.
     *
     * @return \App\Controller\AnthropometryRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::evaluationsByJoueur()": the $anthropometryRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\AnthropometryRepository". Did you forget to add a use statement?');
    }
}
