<?php

namespace ContainerWJdMZGQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T5u3BCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T5u3B_C' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T5u3B_C'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clubRepository' => ['privates', 'App\\Repository\\ClubRepository', 'getClubRepositoryService', true],
            'espaceRepository' => ['privates', 'App\\Repository\\EspacesportifRepository', 'getEspacesportifRepositoryService', true],
            'historiqueRepository' => ['privates', 'App\\Repository\\HistoriqueClubRepository', 'getHistoriqueClubRepositoryService', true],
            'joueurRepository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
            'matchRepository' => ['privates', 'App\\Repository\\MatchEntityRepository', 'getMatchEntityRepositoryService', true],
            'sponsoringRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
        ], [
            'clubRepository' => 'App\\Repository\\ClubRepository',
            'espaceRepository' => 'App\\Repository\\EspacesportifRepository',
            'historiqueRepository' => 'App\\Repository\\HistoriqueClubRepository',
            'joueurRepository' => 'App\\Repository\\JoueurRepository',
            'matchRepository' => 'App\\Repository\\MatchEntityRepository',
            'sponsoringRepository' => 'App\\Repository\\SponsorRepository',
        ]);
    }
}
