<?php

namespace ContainerWJdMZGQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getScheduleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ScheduleController' shared autowired service.
     *
     * @return \App\Controller\ScheduleController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ScheduleController.php';

        $container->services['App\\Controller\\ScheduleController'] = $instance = new \App\Controller\ScheduleController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), '2a65b6315ab7460f97ac49687599263d');

        $instance->setContainer(($container->privates['.service_locator.DZQnY04'] ?? $container->load('get_ServiceLocator_DZQnY04Service'))->withContext('App\\Controller\\ScheduleController', $container));

        return $instance;
    }
}
