parameters:
    profile_pictures_directory: '%kernel.project_dir%/public/uploads/profile_pictures'
    club_photos_directory: '%kernel.project_dir%/public/uploads/club_photos'
    photos_directory: '%kernel.project_dir%/public/uploads/photos'
    materiels_directory: '%kernel.project_dir%/public/uploads/materiels'
    slack.webhook_url: '%env(SLACK_WEBHOOK_URL)%'
    app.base_url: '%env(APP_BASE_URL)%'

services:

    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $botToken: '%env(SLACK_BOT_TOKEN)%'
            $defaultChannel: '#logistique'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'