<?php

namespace ContainerHd37Wf2;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_7ZPrq4tService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7ZPrq4t' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7ZPrq4t'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contratRepository' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'sponsorRepository' => ['privates', 'App\\Repository\\SponsorRepository', 'getSponsorRepositoryService', true],
        ], [
            'contratRepository' => 'App\\Repository\\ContratRepository',
            'sponsorRepository' => 'App\\Repository\\SponsorRepository',
        ]);
    }
}
