<?php

namespace ContainerOwbzvNa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaterielService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DBl8PzK.App\Entity\Materiel' shared service.
     *
     * @return \App\Entity\Materiel
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DBl8PzK": it needs an instance of "App\\Entity\\Materiel" but this type has been excluded in "config/services.yaml".');
    }
}
