<?php

namespace ContainerMiy1bgG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CX9LPYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cX9LP_Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cX9LP_Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'sportRepository' => ['privates', 'App\\Repository\\SportRepository', 'getSportRepositoryService', true],
        ], [
            'sportRepository' => 'App\\Repository\\SportRepository',
        ]);
    }
}
