<?php

namespace Container30QlR3T;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_DXsbKV3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.DXsbKV3' shared service.
     *
     * @return \App\Controller\FlexibilityEvaluationRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\EvaluationPhysiqueController::evaluationsByJoueur()": the $flexibilityEvaluationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\FlexibilityEvaluationRepository". Did you forget to add a use statement?');
    }
}
