<?php

namespace ContainerNELt5DT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U72HKS8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.U72HKS8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.U72HKS8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'joueurRepository' => ['privates', 'App\\Repository\\JoueurRepository', 'getJoueurRepositoryService', true],
            'performanceJoueurRepository' => ['privates', 'App\\Repository\\PerformanceJoueurRepository', 'getPerformanceJoueurRepositoryService', true],
        ], [
            'joueurRepository' => 'App\\Repository\\JoueurRepository',
            'performanceJoueurRepository' => 'App\\Repository\\PerformanceJoueurRepository',
        ]);
    }
}
