<?php

namespace ContainerNELt5DT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getClubControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ClubController' shared autowired service.
     *
     * @return \App\Controller\ClubController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ClubController.php';

        $container->services['App\\Controller\\ClubController'] = $instance = new \App\Controller\ClubController(($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), ($container->privates['debug.validator'] ?? self::getDebug_ValidatorService($container)));

        $instance->setContainer(($container->privates['.service_locator.5zAhzgv'] ?? $container->load('get_ServiceLocator_5zAhzgvService'))->withContext('App\\Controller\\ClubController', $container));

        return $instance;
    }
}
