<?php

namespace ContainerC7lpljx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Obc2mS2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.obc2mS2' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.obc2mS2'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contratRepository' => ['privates', 'App\\Repository\\ContratRepository', 'getContratRepositoryService', true],
            'stripeClient' => ['privates', 'Stripe\\StripeClient', 'getStripeClientService', true],
        ], [
            'contratRepository' => 'App\\Repository\\ContratRepository',
            'stripeClient' => 'Stripe\\StripeClient',
        ]);
    }
}
