<?php

namespace ContainerC7lpljx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0AreAVXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0AreAVX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0AreAVX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'historiqueClub' => ['privates', '.errored..service_locator.0AreAVX.App\\Entity\\HistoriqueClub', NULL, 'Cannot autowire service ".service_locator.0AreAVX": it needs an instance of "App\\Entity\\HistoriqueClub" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'historiqueClub' => 'App\\Entity\\HistoriqueClub',
        ]);
    }
}
