<?php

namespace Container2QxxJMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AiPg5ATService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aiPg5AT' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aiPg5AT'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'eventIdStorage' => ['privates', 'App\\Service\\EventIdStorage', 'getEventIdStorageService', true],
        ], [
            'eventIdStorage' => 'App\\Service\\EventIdStorage',
        ]);
    }
}
