<?php

namespace Container2QxxJMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZHZGuMHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zHZGuMH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zHZGuMH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'eventIdStorage' => ['privates', 'App\\Service\\EventIdStorage', 'getEventIdStorageService', true],
            'googleCalendarService' => ['privates', 'App\\Service\\GoogleCalendarService', 'getGoogleCalendarServiceService', true],
        ], [
            'entityManager' => '?',
            'eventIdStorage' => 'App\\Service\\EventIdStorage',
            'googleCalendarService' => 'App\\Service\\GoogleCalendarService',
        ]);
    }
}
