<?php

namespace Container2QxxJMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_SIgc0LService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.sIgc_0L' shared service.
     *
     * @return \App\Repository\MatchsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\DashboardController::index()": the $matchsRepository argument is type-hinted with the non-existent class or interface: "App\\Repository\\MatchsRepository".');
    }
}
