<?php

namespace Container2QxxJMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P62U6Y0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P62U6Y0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P62U6Y0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'espaceSportifRepository' => ['privates', 'App\\Repository\\EspacesportifRepository', 'getEspacesportifRepositoryService', true],
            'geocodingService' => ['privates', 'App\\Service\\GeocodingService', 'getGeocodingServiceService', true],
            'scheduleRepository' => ['privates', 'App\\Repository\\ScheduleRepository', 'getScheduleRepositoryService', true],
        ], [
            'espaceSportifRepository' => 'App\\Repository\\EspacesportifRepository',
            'geocodingService' => 'App\\Service\\GeocodingService',
            'scheduleRepository' => 'App\\Repository\\ScheduleRepository',
        ]);
    }
}
