<?php

namespace Container2QxxJMd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\GeminiController' shared autowired service.
     *
     * @return \App\Controller\GeminiController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'GeminiController.php';

        $container->services['App\\Controller\\GeminiController'] = $instance = new \App\Controller\GeminiController($container->getEnv('GEMINI_API_KEY'));

        $instance->setContainer(($container->privates['.service_locator.5zAhzgv'] ?? $container->load('get_ServiceLocator_5zAhzgvService'))->withContext('App\\Controller\\GeminiController', $container));

        return $instance;
    }
}
