<?php

namespace ContainerNPZgO8A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8te4nbtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8te4nbt' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8te4nbt'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'clubRepository' => ['privates', 'App\\Repository\\ClubRepository', 'getClubRepositoryService', true],
            'knpSnappyPdf' => ['privates', 'Knp\\Snappy\\Pdf', 'getPdfService', true],
        ], [
            'clubRepository' => 'App\\Repository\\ClubRepository',
            'knpSnappyPdf' => 'Knp\\Snappy\\Pdf',
        ]);
    }
}
