<?php

namespace ContainerAkSYx0V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHistoriqueClub2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4E2JJj5.App\Entity\HistoriqueClub' shared service.
     *
     * @return \App\Entity\HistoriqueClub
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4E2JJj5": it needs an instance of "App\\Entity\\HistoriqueClub" but this type has been excluded in "config/services.yaml".');
    }
}
