<?php

namespace ContainerAkSYx0V;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSlackNotifierService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\SlackNotifier' shared autowired service.
     *
     * @return \App\Service\SlackNotifier
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'SlackNotifier.php';

        return $container->privates['App\\Service\\SlackNotifier'] = new \App\Service\SlackNotifier($container->getEnv('SLACK_BOT_TOKEN'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)), '#logistique');
    }
}
