<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiy1bgG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiy1bgG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMiy1bgG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMiy1bgG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMiy1bgG\App_KernelDevDebugContainer([
    'container.build_hash' => 'Miy1bgG',
    'container.build_id' => 'e10c9c6f',
    'container.build_time' => 1743900318,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiy1bgG');
