<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA4XBJaJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA4XBJaJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA4XBJaJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA4XBJaJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA4XBJaJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'A4XBJaJ',
    'container.build_id' => 'df007cbf',
    'container.build_time' => 1744500730,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA4XBJaJ');
