<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX57mxvw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX57mxvw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX57mxvw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX57mxvw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX57mxvw\App_KernelDevDebugContainer([
    'container.build_hash' => 'X57mxvw',
    'container.build_id' => 'a227207e',
    'container.build_time' => 1744053162,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX57mxvw');
