<?php

namespace ContainerE6OwAeP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerformanceJoueurService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.PNlbJGO.App\Entity\PerformanceJoueur' shared service.
     *
     * @return \App\Entity\PerformanceJoueur
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.PNlbJGO": it needs an instance of "App\\Entity\\PerformanceJoueur" but this type has been excluded in "config/services.yaml".');
    }
}
